-- V218: safe, additive migration for existing projects. No player data is deleted.
begin;
alter table public.chaldea_expenses add column if not exists types text[] not null default '{}'::text[];
alter table public.chaldea_expenses add column if not exists characters jsonb not null default '[]'::jsonb;
grant select, insert, update, delete on table public.chaldea_expenses to authenticated;
grant usage, select on sequence public.chaldea_expenses_id_seq to authenticated;
create or replace function public.claim_julien()
returns void language plpgsql security definer set search_path = public as $$
begin
  raise exception 'Un administrateur doit associer le compte à un Master.';
end;
$$;
revoke all on function public.claim_julien() from public, anon, authenticated;
-- GSSR history: one editable result per player and event, readable to authenticated Masters.
create table if not exists public.chaldea_gssr_results(
  id bigint generated by default as identity primary key,
  player_key text not null references public.chaldea_members(player_key) on delete cascade,
  event_id text not null,
  selected_pool_id text,
  destiny_choices jsonb not null default '{}'::jsonb,
  obtained_servants jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique(player_key,event_id)
);
alter table public.chaldea_gssr_results enable row level security;
drop policy if exists gssr_results_read_authenticated on public.chaldea_gssr_results;
create policy gssr_results_read_authenticated on public.chaldea_gssr_results for select to authenticated using (true);
drop policy if exists gssr_results_insert_self on public.chaldea_gssr_results;
create policy gssr_results_insert_self on public.chaldea_gssr_results for insert to authenticated with check (
  player_key = (select player_key from public.chaldea_members where auth_user_id = auth.uid() limit 1)
  and exists (select 1 from public.chaldea_members m where m.auth_user_id=auth.uid() and m.player_key=chaldea_gssr_results.player_key and m.can_edit=true)
);
drop policy if exists gssr_results_update_self on public.chaldea_gssr_results;
create policy gssr_results_update_self on public.chaldea_gssr_results for update to authenticated using (
  player_key = (select player_key from public.chaldea_members where auth_user_id = auth.uid() limit 1)
  and exists (select 1 from public.chaldea_members m where m.auth_user_id=auth.uid() and m.player_key=chaldea_gssr_results.player_key and m.can_edit=true)
) with check (
  player_key = (select player_key from public.chaldea_members where auth_user_id = auth.uid() limit 1)
  and exists (select 1 from public.chaldea_members m where m.auth_user_id=auth.uid() and m.player_key=chaldea_gssr_results.player_key and m.can_edit=true)
);
drop policy if exists gssr_results_delete_self on public.chaldea_gssr_results;
create policy gssr_results_delete_self on public.chaldea_gssr_results for delete to authenticated using (
  player_key = (select player_key from public.chaldea_members where auth_user_id = auth.uid() limit 1)
  and exists (select 1 from public.chaldea_members m where m.auth_user_id=auth.uid() and m.player_key=chaldea_gssr_results.player_key and m.can_edit=true)
);
grant select, insert, update, delete on table public.chaldea_gssr_results to authenticated;
grant usage, select on sequence public.chaldea_gssr_results_id_seq to authenticated;

commit;
